image: "ruby:2.3"

services:
  - postgres:latest

cache:
  paths:
    - vendor/bundle

variables:
  POSTGRES_DB: taskr_test
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: ""
  DB_HOST: postgres


before_script:

   # Setup VPN
  - apt-get update -y
  - apt-get install -y debconf openssl

  - wget http://cdn.kerio.com/dwn/control/control-9.2.7-2921/kerio-control-vpnclient-9.2.7-2921-linux-amd64.deb
  - chmod +x ./bin/kerio_setup
  - ./bin/kerio_setup $VPN_SERVER $USERNAME $PASSWORD
  - apt-get -f install -y
  - /etc/init.d/kerio-kvc restart
  - sleep 5s
  - cat /var/log/kerio-kvc/error.log
  - cat /var/log/kerio-kvc/debug.log
  - ping -c 5 'nexus.devfactory.com'
  

    # Install node and some other deps
  - curl -sL https://deb.nodesource.com/setup_8.x | bash -
  - apt-get install -y apt-transport-https build-essential cmake nodejs software-properties-common unzip
  
  # Install yarn
  - wget -q -O - https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list
  - apt-get install -y yarn

  # Project setup
  - bundle check || bundle install --jobs $(nproc)
  - yarn install
  - apt-get update -qq && apt-get install -y -qq postgresql postgresql-contrib libpq-dev cmake
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - bundle install --quiet
  - RAILS_ENV=test bundle install --jobs $(nproc) "${FLAGS[@]}"
  - cp config/database.yml.gitlab config/database.yml
  - RAILS_ENV=test bundle exec rake db:create db:schema:load
  - RAILS_ENV=test bundle exec rake db:migrate --quiet
  - RAILS_ENV=test bundle exec rake db:test:prepare --quiet

rspec:
  script:
    - RAILS_ENV=test bundle exec rspec

cucumber:
  script:
  - RAILS_ENV=test bundle exec cucumber

production:
  stage: deploy
  retry: 2
  only:
    - develop
  script:
  - chmod +x ./bin/setup_heroku
  - ./bin/setup_heroku
  - dpl --provider=heroku --app=ca-taskr-dev --api-key=$HEROKU_PRODUCTION_API_KEY
  - heroku run rake db:migrate --exit-code --app ca-taskr-dev
  - heroku run rake statics:seed --exit-code --app ca-taskr-dev